# Generated by Django 3.2.4 on 2021-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default='Unknown', max_length=120, null=True),
        ),
    ]
